alter table KAUST_MODEL add constraint FK_KAUST_MODEL_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
create index IDX_KAUST_MODEL_ON_FILE_DESCRIPTOR on KAUST_MODEL (FILE_DESCRIPTOR_ID);
